### ISSUE TITLE
Connecticut has been the answer for the past 3 days

### ISSUE THREAD

**Issue by jpozin** [eoncarlyle/state-economy-game#45]
Beginning two days ago thru today (12/7-12/9), the state of the day was Connecticut.

**Comment by eoncarlyle** [comment]
Dear valued player @jpozin,

Exactly 51 days before Connecticut was selected the first time, I stopped deleted obsolete puzzle answers. Because of the way I was creating new puzzle answers this meant that a new puzzle answer wasn't created because all possible options were still in the puzzle answer table. I regret the error and a fix will be out in a day or two.

Iain

**Comment by jpozin** [comment]
Thanks for the RCA and prompt fix!

**Comment by eoncarlyle** [comment]
@jpozin overnight a non-Connecticut answer was selected by the game, so I will now close this issue!

**Comment by eoncarlyle** [comment]
@jpozin I kinda yolo'd a MR this evening, I don't think that this will disrupt anything but please do report any possible bugs that come up in the days to come

https://github.com/eoncarlyle/state-economy-game/pull/46
